# place both the bot and the config file into the same folder as your start.bat file

# Change this to the name of your start.bat file
# Example: startserver.bat
startdir: ""

# Set this to true of false depending on whether you are using playit.gg to run your server
playit: "false"

# Add your Discord Bot token.
# To get a token follow this tutorial: https://youtu.be/ic5GuP-uHcg
# To invite the bot to your server go to the OAuth2 Tab on your discord bot then tick the 'bot' box under scopes,
# and 'send messages' under permissions. Finally copy the link at the bottom into a browser.
token: ""
